// @generated by tools/gen_cases.py — a mechanical arithmetic case.

#include <stdio.hh>
"%d\n", 1024 << 0;
"%d\n", 1024 << 1;
"%d\n", 1024 << 4;
"%d\n", 1024 << 8;
"%d\n", 1024 << 16;
"%d\n", 1024 << 31;
