// @generated by tools/gen_cases.py — a mechanical arithmetic case.

#include <stdio.hh>
"%d\n", 123456 >> 0;
"%d\n", 123456 >> 1;
"%d\n", 123456 >> 4;
"%d\n", 123456 >> 8;
"%d\n", 123456 >> 16;
"%d\n", 123456 >> 31;
