// @generated by tools/gen_cases.py — a mechanical relational case.
"%d %d\n", 0 && 0, 0 || 0;
"%d %d\n", 0 && 1, 0 || 1;
"%d %d\n", 1 && 0, 1 || 0;
"%d %d\n", 1 && 1, 1 || 1;
"%d %d\n", 5 && 0, 5 || 0;
