// @generated by tools/gen_cases.py — a mechanical stdio_printf case.
"%i\n", 0;
"%i\n", 1;
"%i\n", -1;
"%i\n", 42;
"%i\n", -42;
"%i\n", 255;
"%i\n", 65535;
"%i\n", 2147483647;
"%i\n", -2147483648;
"%i\n", 1000000;
