// @generated by tools/gen_cases.py — a mechanical stdio_printf case.
"%u\n", 0;
"%u\n", 1;
"%u\n", -1;
"%u\n", 42;
"%u\n", -42;
"%u\n", 255;
"%u\n", 65535;
"%u\n", 2147483647;
"%u\n", -2147483648;
"%u\n", 1000000;
