// @generated by tools/gen_cases.py — a mechanical stdio_printf case.
"%o\n", 0;
"%o\n", 1;
"%o\n", -1;
"%o\n", 42;
"%o\n", -42;
"%o\n", 255;
"%o\n", 65535;
"%o\n", 2147483647;
"%o\n", -2147483648;
"%o\n", 1000000;
