// @generated by tools/gen_cases.py — a mechanical stdio_printf case.
"%d\n", 0;
"%d\n", 1;
"%d\n", -1;
"%d\n", 42;
"%d\n", -42;
"%d\n", 255;
"%d\n", 65535;
"%d\n", 2147483647;
"%d\n", -2147483648;
"%d\n", 1000000;
