//! Compile-time test generation for the `hcc` integration and comparison suites.
//!
//! These function-like proc-macros glob the test-case tree at expansion time and emit one
//! `#[test]` per case — the role the old `build.rs` (and `tools/gen_cases.py`) played, now
//! pure Rust with no build script. They run during the compilation of the consuming crate,
//! so `CARGO_MANIFEST_DIR` is the `hcc` package root.
//!
//! Caveat vs a build script: each generated `include_str!` makes editing a `.hc` re-trigger
//! compilation, but **adding or removing** a case is not auto-detected (the glob result is
//! baked into the expansion). After adding/removing a `.hc`, force a rebuild of the test
//! crate (`touch tests/integration.rs`, or `cargo clean -p hcc`).

use proc_macro::TokenStream;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

/// Emit one `#[test] fn` per `tests/<dir>/**/*.hc`, where `<dir>` is the string-literal
/// argument (e.g. `test_case!("cases")`). Each test calls `run_case(rel, src)` (which must be
/// in scope at the call site) with `rel` the case path **relative to `tests/`**, so the
/// golden (`<case>.out`) and any local `#include` resolve from there. The test ident is that
/// relative path, so names stay unique across — and labelled by — the directory.
#[proc_macro]
pub fn test_case(input: TokenStream) -> TokenStream {
    let dir = str_lit(input);
    let tests = manifest_dir().join("tests");
    let mut files = Vec::new();
    collect_hc(&tests.join(&dir), &mut files);
    files.sort();

    let mut out = format!("// generated by hcc_test_macros::test_case!({dir:?})\n");
    let mut seen = HashSet::new();
    for path in &files {
        let rel = path
            .strip_prefix(&tests)
            .unwrap()
            .to_string_lossy()
            .replace('\\', "/");
        let ident = sanitize(&rel, &mut seen);
        out.push_str(&format!(
            "#[test] fn {ident}() {{ run_case({rel:?}, include_str!({:?})); }}\n",
            path.to_string_lossy(),
        ));
    }
    out.parse().expect("generated tests must parse")
}

/// The single string-literal argument of a function-like macro, with its quotes stripped.
fn str_lit(input: TokenStream) -> String {
    let s = input.to_string();
    let t = s.trim();
    t.strip_prefix('"')
        .and_then(|t| t.strip_suffix('"'))
        .unwrap_or(t)
        .to_string()
}

/// Emit one `#[test] fn bench_<name>` per `tests/bench/<name>/` holding `prog.hc` + `prog.c`,
/// each calling `run_comparison(name)` (which must be in scope). Invoke at module level.
#[proc_macro]
pub fn comparison_cases(_input: TokenStream) -> TokenStream {
    let root = manifest_dir();
    let bench = root.join("tests").join("bench");
    let mut names = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&bench) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.join("prog.hc").is_file() && p.join("prog.c").is_file() {
                if let Some(name) = p.file_name().and_then(|n| n.to_str()) {
                    names.push(name.to_string());
                }
            }
        }
    }
    names.sort();

    let mut out = String::from("// generated by hcc_test_macros::comparison_cases!\n");
    let mut seen = HashSet::new();
    for name in &names {
        let ident = sanitize(name, &mut seen);
        out.push_str(&format!(
            "#[test] fn bench_{ident}() {{ run_comparison({name:?}); }}\n"
        ));
    }
    out.parse().expect("generated comparison tests must parse")
}

/// The consuming crate's manifest directory (the `hcc` package root) — set by Cargo in
/// the rustc process that runs this macro.
fn manifest_dir() -> PathBuf {
    PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"))
}

/// Recursively collect every `*.hc` under `dir` (silently no-op if `dir` is absent).
fn collect_hc(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            collect_hc(&p, out);
        } else if p.extension().is_some_and(|x| x == "hc") {
            out.push(p);
        }
    }
}

/// Turn a `category/sub/name.hc` relative path (or a bench dir name) into a unique
/// snake_case test ident.
fn sanitize(rel: &str, seen: &mut HashSet<String>) -> String {
    let stem = rel.strip_suffix(".hc").unwrap_or(rel);
    let mut s = String::with_capacity(stem.len());
    let mut prev_us = false;
    for ch in stem.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch.to_ascii_lowercase());
            prev_us = false;
        } else if !prev_us {
            s.push('_');
            prev_us = true;
        }
    }
    let mut base: String = s.trim_matches('_').to_string();
    if base.is_empty() {
        base = "case".to_string();
    }
    if base.as_bytes()[0].is_ascii_digit() {
        base.insert_str(0, "c_");
    }
    let mut name = base.clone();
    let mut n = 2;
    while !seen.insert(name.clone()) {
        name = format!("{base}_{n}");
        n += 1;
    }
    name
}
