// @generated by tools/gen_cases.py — a mechanical stdio_printf case.

#include <stdio.hh>
"%X\n", 0;
"%X\n", 1;
"%X\n", -1;
"%X\n", 42;
"%X\n", -42;
"%X\n", 255;
"%X\n", 65535;
"%X\n", 2147483647;
"%X\n", -2147483648;
"%X\n", 1000000;
